In [95]:
import numpy as np
print("Hello World")

Hello World


In [96]:
print("this is amazinng")

this is amazinng


**This is markdown sentance**

#this is markdown title

In [97]:

firstarray =np.array([354, 3543, 32,2,2])

In [98]:
firstarray

array([ 354, 3543,   32,    2,    2])

In [99]:
firstarray[0]
firstarray[1]

3543

In [100]:
firstarray.size

5

In [101]:
zerosmatrix = np.zeros((3,3), dtype =np.int8)

In [102]:
zerosmatrix

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [103]:
zerosmatrix[0,2] = 23
zerosmatrix

array([[ 0,  0, 23],
       [ 0,  0,  0],
       [ 0,  0,  0]], dtype=int8)

In [104]:
zerosmatrix[1,1] = 2342
zerosmatrix

array([[ 0,  0, 23],
       [ 0, 38,  0],
       [ 0,  0,  0]], dtype=int8)

** Array Creation : using python elements **

In [105]:
listarray = np.array([[1,45,6],[3,76,7],[3,8,8],[34,4,7]])

In [106]:
listarray

array([[ 1, 45,  6],
       [ 3, 76,  7],
       [ 3,  8,  8],
       [34,  4,  7]])

In [107]:
listarray.dtype

dtype('int32')

In [108]:
listarray.shape

(4, 3)

In [109]:
tupplearray =np.array([{1,4,7,4},{1,5,7},{1,2}])

In [110]:
tupplearray
type(tupplearray[2])

set

In [111]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [112]:
arange_array =  np.arange(12)
arange_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [113]:
lspace_arr= np.linspace(1,6,4)
lspace_arr

array([1.        , 2.66666667, 4.33333333, 6.        ])

In [114]:
empty_arr = np.empty((2,5)) #random array
empty_arr

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.02360527e-306, 1.33511562e-306],
       [1.42413555e-306, 1.78019082e-306, 1.37959740e-306,
        6.23057349e-307, 1.42419530e-306]])

In [115]:
empty_like_arr = np.empty_like(lspace_arr)
empty_like_arr

array([1.        , 2.66666667, 4.33333333, 6.        ])

In [116]:
identity_mtx= np.identity(3)
identity_mtx

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [117]:
lspace_arr2 = np.arange(99)
lspace_arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [118]:
lspace_arr2.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [119]:
arange_arr_ls2 = lspace_arr2.reshape(3,33)
arange_arr_ls2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [120]:
arange_arr_ls2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [121]:
sample_arr_py = [[1,3,56,3],[1,4,5,2],[3,3,1,4]]
sample_arr_np = np.array(sample_arr_py)

In [122]:
sample_arr_np.sum()

86

In [123]:
sample_arr_np.sum(axis=0)

array([ 5, 10, 62,  9])

In [124]:
sample_arr_np.sum(axis=1)

array([63, 12, 11])

In [125]:
sample_arr_np.T

array([[ 1,  1,  3],
       [ 3,  4,  3],
       [56,  5,  1],
       [ 3,  2,  4]])

In [126]:
sample_arr_np.flat

In [127]:
for item in sample_arr_np.flat:
    print(f"{item}")

1
3
56
3
1
4
5
2
3
3
1
4


In [128]:
sample_arr_np.ndim

2

In [129]:
sample_arr_np.nbytes

48

In [130]:
oneDarr = np.array([1,4,5,2])

In [131]:
oneDarr.argmax()

2

In [132]:
oneDarr.argsort()

array([0, 3, 1, 2], dtype=int64)

In [133]:
sample_arr_np.argsort()

array([[0, 1, 3, 2],
       [0, 3, 1, 2],
       [2, 0, 1, 3]], dtype=int64)

In [134]:
sample_arr_np.argmax()

2

In [135]:
sample_arr_np.argmin(axis=1)

array([0, 0, 2], dtype=int64)

In [136]:
sample_arr_np1 = np.empty_like(sample_arr_np)
sample_arr_np1

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [137]:
sample_arr_np1 + sample_arr_np

array([[ 1,  3, 56,  3],
       [ 1,  4,  5,  2],
       [ 3,  3,  1,  4]])

In [138]:
sample_arr_np * sample_arr_np1

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [139]:
np.sqrt(sample_arr_np)

array([[1.        , 1.73205081, 7.48331477, 1.73205081],
       [1.        , 2.        , 2.23606798, 1.41421356],
       [1.73205081, 1.73205081, 1.        , 2.        ]])

In [140]:
np.where(sample_arr_np1>600)

(array([], dtype=int64), array([], dtype=int64))

In [141]:
import sys

In [142]:
sys.getsizeof(1)*len(sample_arr_py)

84

In [94]:
sys.getsizeof(sample_arr_py)

80

In [91]:
sample_arr_np.itemsize*sample_arr_np.size

48

In [93]:
sys.getsizeof(sample_arr_np)

176